title: Iterated learning for emergent systematicity in VQA
description: Ankit Vani, Max Schwarzer, Yuchen Lu, Eeshan Dhekane, Aaron Courville
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
